# I Created a DataBase Called "Titanic_dataset"  Which Contain all the Information about Passengers and Port details.

USE titanic_dataset;     
# USE keyword help to select a Specific Database from Multiple Databases

 # Imported a tables called "Titanic" and "Ports" into database
SELECT * FROM Titanic;
SELECT * FROM Ports;


# --- Checking Null Values -- 
# In Result Grid All Columns are Empty which makes there are NO Null Values in the Dataset
# But Cabin Column has all Blank values, So I use Drop function to Remove Permanently. 
SELECT * FROM titanic WHERE fare IS NULL;
SELECT * FROM ports WHERE portcode IS NULL;


# --- DROP FUNCTION ---
# I dropped the Cabin Which contain Blanks(null)
ALTER table Titanic
DROP cabin;

# --- ANALYSIS--

# 1 . Let's know how many passengers from different Gender.
# here I perform Group by function to know how many male and female Passengers
# count gives the total Values of Coulumn.
SELECT sex, count(*) AS Passanger_Count 
FROM titanic
GROUP BY sex;

# 2 . How many people Survived as per Age
SELECT sex, survived, count(*) AS Survived_Gender 
FROM titanic
WHERE age > 18 AND  survived = 0
GROUP BY Survived , sex;


# --- CASE STATEMENT ---

# Here Case statements are used to Know the Agegroup of passenges
SELECT name,
CASE
WHEN age < 18 then "Child"
WHEN age > 18 then "Adult"
ELSE "Old"
END AS "AgeGroup"
FROM titanic;


# --- Revenue ---

#Total Revenue using Aggregate Functions
# SUM is used to Calculate all the rows of a Value.
SELECT Embarked , SUM(Fare)  AS Total_Revenue
 FROM titanic;

# How Much Revenue for Each PortCode/Embarked
# Here, I use Groupby and Orderby clause to analyse which port is Generating more Revenue
SELECT Embarked , SUM(Fare)  AS Total_Revenue 
FROM titanic
GROUP BY embarked
ORDER BY Total_Revenue DESC;

# Here AVG function gives the how much revenue is generated by Each Class
SELECT Pclass, AVG(Fare) AS avg_fare
FROM titanic
GROUP BY Pclass
ORDER BY avg_fare DESC;


# --- JOINS ---
# Here , I have another table called "PORTS" which contain Embarked code in titatnic table.
# So, I use InnerJoin to join these two tables.

SELECT * FROM titanic t 
INNER JOIN ports p 
ON t.embarked = p.portcode;

SELECT t.Name, t.Sex, t.Embarked, p.PortName, p.Country
FROM titanic t
LEFT JOIN ports p
ON t.Embarked = p.PortCode;

SELECT Name , p.country , sex
FROM titanic t 
RIGHT JOIN ports p ON p.portcode = t.Embarked
WHERE Survived = 0;


# --- SUB QUERY ---

SELECT Name, Pclass, Fare
FROM titanic
WHERE Fare > (SELECT AVG(Fare) FROM titanic);

SELECT Name 
FROM titanic
WHERE PassengerId IN (
  SELECT PassengerId
  FROM titanic
  WHERE Survived = 1 AND Pclass = 1
);


